### ISSUE TITLE
Keyboard just disappears once input is empty

### ISSUE THREAD

**Issue by probablyjosh** [cosmiclabsio/echo-ios#13]
<img width="487" alt="screen shot 2015-08-04 at 6 21 40 pm" src="https://cloud.githubusercontent.com/assets/4617414/9076330/fc0d645e-3ad5-11e5-81fd-7cb9c93a3f3b.png">

No way to bring keyboard back up again
![what](https://cloud.githubusercontent.com/assets/4617414/9076436/0a766918-3ad7-11e5-8ce4-b320a2cbbacf.gif)

**Comment by istx25** [comment]
Make sure you've toggled the software keyboard in the iOS Simulator (⌘+K)

<img width="614" alt="screen shot 2015-08-05 at 4 08 28 pm" src="https://cloud.githubusercontent.com/assets/6799989/9089337/9b5c7ea8-3b8c-11e5-927c-5850965276a2.png">
